/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccountingPeriod {
  'to' : [] | [Timestamp],
  'from' : [] | [Timestamp],
}
export interface AccountingReport {
  'byPaymentMethod' : Array<PaymentMethodBreakdown>,
  'entries' : Array<LedgerEntry>,
  'summary' : AccountingSummary,
  'byExpenseCategory' : Array<CategoryBreakdown>,
  'profit' : ProfitBreakdown,
}
export interface AccountingSummary {
  'to' : [] | [Timestamp],
  'expenseCount' : bigint,
  'invoiceCount' : bigint,
  'from' : [] | [Timestamp],
  'totalIncome' : Money,
  'totalExpenses' : Money,
  'profit' : bigint,
}
export type AdjustmentDirection = { 'in' : null } |
  { 'out' : null };
export interface AdjustmentInput {
  'direction' : AdjustmentDirection,
  'lotId' : [] | [Id],
  'quantity' : bigint,
  'partId' : Id,
  'reason' : string,
}
export interface Appointment {
  'id' : Id,
  'status' : AppointmentStatus,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'durationMinutes' : bigint,
  'technicianId' : [] | [Id],
  'motorcycleId' : Id,
  'customerId' : Id,
  'scheduledAt' : Timestamp,
  'reason' : string,
}
export interface AppointmentFilter {
  'to' : [] | [Timestamp],
  'status' : [] | [AppointmentStatus],
  'from' : [] | [Timestamp],
  'technicianId' : [] | [Id],
}
export interface AppointmentInput {
  'durationMinutes' : bigint,
  'technicianId' : [] | [Id],
  'motorcycleId' : Id,
  'customerId' : Id,
  'scheduledAt' : Timestamp,
  'reason' : string,
}
export type AppointmentStatus = { 'scheduled' : null } |
  { 'noShow' : null } |
  { 'cancelled' : null } |
  { 'attended' : null } |
  { 'confirmed' : null };
export type BackupError = { 'notAuthorized' : null } |
  { 'driveFailed' : string } |
  { 'notConnected' : null };
export interface BackupFile {
  'name' : string,
  'createdAt' : bigint,
  'size' : bigint,
  'fileId' : string,
  'webViewLink' : string,
}
export type BackupListOutcome = { 'ok' : Array<BackupFile> } |
  { 'err' : BackupError };
export type BackupOutcome = { 'ok' : BackupResult } |
  { 'err' : BackupError };
export interface BackupResult {
  'name' : string,
  'createdAt' : bigint,
  'size' : bigint,
  'fileId' : string,
  'webViewLink' : string,
}
export type BasisPoints = bigint;
export interface BulkResult {
  'created' : bigint,
  'skipped' : bigint,
  'rows' : Array<BulkRowResult>,
  'updated' : bigint,
  'failed' : bigint,
}
export interface BulkRowResult {
  'id' : [] | [Id],
  'ok' : boolean,
  'error' : [] | [string],
  'index' : bigint,
}
export interface BusinessSettings {
  'taxId' : string,
  'name' : string,
  'address' : string,
  'phone' : string,
  'taxRate' : TaxRate,
}
export interface CategoryBreakdown { 'total' : Money, 'category' : string }
export interface Cell { 'value' : Value, 'name' : string }
export interface CommissionLine {
  'at' : Timestamp,
  'serviceDate' : Timestamp,
  'laborId' : Id,
  'serviceName' : string,
  'motorcycleModel' : string,
  'technicianCode' : string,
  'technicianName' : string,
  'description' : string,
  'orderId' : Id,
  'technicianId' : Id,
  'baseAmount' : Money,
  'commissionAmount' : Money,
  'commissionRate' : bigint,
  'serviceId' : Id,
  'motorcycleBrand' : string,
  'motorcyclePlate' : string,
  'orderNumber' : string,
}
export interface CommissionPayment {
  'id' : Id,
  'technicianCode' : string,
  'technicianName' : string,
  'period' : CommissionPeriod,
  'netPaid' : Money,
  'loansDeducted' : Money,
  'lines' : Array<CommissionLine>,
  'loans' : Array<CommissionPaymentLoan>,
  'lineCount' : bigint,
  'technicianId' : Id,
  'baseAmount' : Money,
  'commissionAmount' : Money,
  'paidAt' : Timestamp,
  'paidBy' : Principal,
}
export interface CommissionPaymentFilter {
  'to' : [] | [Timestamp],
  'from' : [] | [Timestamp],
  'technicianId' : [] | [Id],
}
export interface CommissionPaymentInput {
  'period' : CommissionPeriod,
  'technicianId' : Id,
}
export interface CommissionPaymentLoan {
  'date' : Timestamp,
  'note' : [] | [string],
  'loanId' : Id,
  'amount' : Money,
}
export interface CommissionPeriod {
  'to' : [] | [Timestamp],
  'from' : [] | [Timestamp],
}
export interface CommissionReport {
  'totalCommission' : Money,
  'technicians' : Array<TechnicianCommissionSummary>,
  'period' : CommissionPeriod,
  'totalNetPayable' : Money,
  'totalBase' : Money,
  'totalPendingLoans' : Money,
}
export interface CompanyProfile {
  'taxId' : string,
  'documentType' : DocumentType,
  'taxResponsibility' : TaxResponsibility,
  'tradeName' : [] | [string],
  'city' : string,
  'fiscalRegime' : FiscalRegime,
  'email' : [] | [string],
  'website' : [] | [string],
  'legalName' : string,
  'updatedAt' : Timestamp,
  'logoUrl' : [] | [string],
  'address' : string,
  'phone' : string,
  'checkDigit' : [] | [bigint],
  'taxRate' : TaxRate,
}
export interface CompanyProfileRawInput {
  'taxId' : string,
  'documentType' : string,
  'taxResponsibility' : string,
  'tradeName' : [] | [string],
  'city' : string,
  'fiscalRegime' : string,
  'email' : [] | [string],
  'website' : [] | [string],
  'legalName' : string,
  'logoUrl' : [] | [string],
  'address' : string,
  'phone' : string,
  'checkDigit' : [] | [bigint],
  'taxRate' : TaxRate,
}
export interface CreateInvoiceInput {
  'kind' : InvoiceFileKind,
  'gatewayUrl' : [] | [string],
  'mimeType' : string,
  'fileName' : string,
  'objectId' : string,
  'projectId' : [] | [string],
  'sizeBytes' : bigint,
}
export interface CreditPlanInput {
  'firstDueDate' : Timestamp,
  'installmentCount' : bigint,
}
export interface Customer {
  'id' : Id,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : [] | [string],
  'document' : [] | [string],
  'address' : [] | [string],
  'phone' : string,
}
export interface CustomerDetail {
  'customer' : Customer,
  'orders' : Array<CustomerOrderSummary>,
  'motorcycles' : Array<Motorcycle>,
}
export interface CustomerExportRow {
  'customer' : Customer,
  'motorcycles' : Array<Motorcycle>,
}
export interface CustomerFilter {
  'search' : [] | [string],
  'hasMotorcycles' : [] | [boolean],
}
export interface CustomerInput {
  'name' : string,
  'email' : [] | [string],
  'document' : [] | [string],
  'address' : [] | [string],
  'phone' : string,
}
export interface CustomerListItem {
  'id' : Id,
  'name' : string,
  'createdAt' : Timestamp,
  'motorcycleCount' : bigint,
  'email' : [] | [string],
  'document' : [] | [string],
  'address' : [] | [string],
  'phone' : string,
}
export interface CustomerNotificationInput {
  'subject' : string,
  'source' : NotificationSource,
  'referenceId' : [] | [Id],
  'message' : string,
  'customerId' : Id,
}
export interface CustomerNotificationResult {
  'sent' : boolean,
  'email' : string,
  'customerId' : Id,
}
export interface CustomerOrderSummary {
  'status' : string,
  'total' : bigint,
  'createdAt' : Timestamp,
  'orderId' : Id,
  'motorcyclePlate' : string,
  'orderNumber' : string,
}
export interface CustomerPage {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'items' : Array<CustomerListItem>,
}
export type CustomerSort = { 'name' : null } |
  { 'createdAt' : null } |
  { 'motorcycleCount' : null };
export interface DashboardSummary {
  'pendingPayablesTotal' : Money,
  'pendingPayablesCount' : bigint,
  'activeOrders' : Array<OrderStatusCount>,
  'lowStock' : Array<LowStockItem>,
}
export type DocumentType = { 'nit' : null } |
  { 'cedulaCiudadania' : null } |
  { 'cedulaExtranjeria' : null };
export interface DriveAuthResult {
  'connected' : boolean,
  'accountEmail' : [] | [string],
}
export interface DriveAuthStart {
  'authorizationUrl' : string,
  'state' : string,
}
export interface DriveConfigStatus {
  'missingVariables' : Array<string>,
  'configured' : boolean,
}
export interface DriveConnectionStatus {
  'connectedAt' : [] | [bigint],
  'connected' : boolean,
  'configuration' : DriveConfigStatus,
  'accountEmail' : [] | [string],
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Expense {
  'id' : Id,
  'tax' : Money,
  'categoryId' : Id,
  'concept' : string,
  'paymentMethod' : string,
  'categoryName' : string,
  'receiptUrl' : [] | [string],
  'supplierName' : [] | [string],
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'amount' : Money,
  'supplierId' : [] | [Id],
}
export interface ExpenseCategory {
  'id' : Id,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
}
export interface ExpenseCategoryFilter { 'search' : [] | [string] }
export interface ExpenseCategoryInput {
  'name' : string,
  'description' : string,
}
export interface ExpenseCategoryTotal {
  'categoryId' : Id,
  'total' : Money,
  'categoryName' : string,
}
export interface ExpenseCategoryUsage {
  'expenseCount' : bigint,
  'category' : ExpenseCategory,
}
export interface ExpenseFilter {
  'to' : [] | [Timestamp],
  'categoryId' : [] | [Id],
  'paymentMethod' : [] | [string],
  'from' : [] | [Timestamp],
  'search' : [] | [string],
}
export interface ExpenseInput {
  'tax' : Money,
  'categoryId' : Id,
  'concept' : string,
  'paymentMethod' : string,
  'receiptUrl' : [] | [string],
  'date' : Timestamp,
  'amount' : Money,
  'supplierId' : [] | [Id],
}
export interface ExpensePage {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'summary' : ExpenseSummary,
  'items' : Array<Expense>,
}
export interface ExpenseSummary {
  'total' : Money,
  'count' : bigint,
  'byCategory' : Array<ExpenseCategoryTotal>,
}
export type ExternalBlob = Uint8Array;
export type ExtractionStatus = { 'pending' : null } |
  { 'extracting' : null } |
  { 'extracted' : null } |
  { 'failed' : null };
export type FiscalRegime = { 'noResponsableIva' : null } |
  { 'responsableIva' : null };
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export type Id = bigint;
export type ImportRowStatus = { 'created' : null } |
  { 'error' : null } |
  { 'updated' : null };
export interface Installment {
  'paid' : boolean,
  'dueDate' : Timestamp,
  'number' : bigint,
  'amount' : Money,
  'paidAt' : [] | [Timestamp],
}
export interface InstallmentPlan {
  'firstDueDate' : Timestamp,
  'installmentCount' : bigint,
  'installments' : Array<Installment>,
}
export interface InventoryCsvRow {
  'sku' : string,
  'lowStockThreshold' : bigint,
  'name' : string,
  'unit' : string,
  'quantity' : bigint,
  'category' : string,
  'salePrice' : Money,
  'brand' : string,
  'costPrice' : Money,
}
export interface InventoryImportResult {
  'created' : bigint,
  'rows' : Array<InventoryImportRowResult>,
  'updated' : bigint,
  'failed' : bigint,
}
export interface InventoryImportRow {
  'sku' : string,
  'lowStockThreshold' : bigint,
  'name' : string,
  'unit' : string,
  'quantity' : bigint,
  'category' : string,
  'salePrice' : Money,
  'brand' : string,
  'costPrice' : Money,
  'rowNumber' : bigint,
}
export interface InventoryImportRowResult {
  'id' : [] | [Id],
  'sku' : string,
  'status' : ImportRowStatus,
  'error' : [] | [string],
  'rowNumber' : bigint,
}
export interface InventoryValuation {
  'rows' : Array<InventoryValuationRow>,
  'totals' : InventoryValuationTotals,
  'byCategory' : Array<InventoryValuationCategory>,
}
export interface InventoryValuationCategory {
  'saleValue' : Money,
  'costValue' : Money,
  'units' : bigint,
  'category' : string,
  'partCount' : bigint,
  'margin' : bigint,
  'marginBps' : BasisPoints,
}
export interface InventoryValuationRow {
  'sku' : string,
  'saleValue' : Money,
  'costValue' : Money,
  'name' : string,
  'units' : bigint,
  'category' : string,
  'margin' : bigint,
  'partId' : Id,
  'marginBps' : BasisPoints,
}
export interface InventoryValuationTotals {
  'totalCostValue' : Money,
  'totalMargin' : bigint,
  'totalUnits' : bigint,
  'partCount' : bigint,
  'marginBps' : BasisPoints,
  'totalSaleValue' : Money,
}
export interface Invoice {
  'id' : Id,
  'tax' : Money,
  'customerName' : string,
  'total' : Money,
  'paymentStatus' : PaymentStatus,
  'posSaleId' : [] | [Id],
  'paymentMethod' : PaymentMethod,
  'origin' : InvoiceOrigin,
  'paymentCondition' : PaymentCondition,
  'orderId' : [] | [Id],
  'lines' : Array<InvoiceLine>,
  'customerTaxId' : [] | [string],
  'customerAddress' : [] | [string],
  'number' : string,
  'discount' : Money,
  'customerId' : [] | [Id],
  'installments' : [] | [InstallmentPlan],
  'issuedAt' : Timestamp,
  'taxRate' : TaxRate,
  'subtotal' : Money,
}
export interface InvoiceApplyLineResult {
  'status' : LineApplyStatus,
  'movementId' : [] | [Id],
  'code' : string,
  'error' : [] | [string],
  'lineNumber' : bigint,
  'lotId' : [] | [Id],
  'lineId' : Id,
  'partId' : [] | [Id],
}
export interface InvoiceApplyResult {
  'status' : PurchaseInvoiceStatus,
  'created' : bigint,
  'invoiceId' : Id,
  'lines' : Array<InvoiceApplyLineResult>,
  'updated' : bigint,
  'failed' : bigint,
}
export type InvoiceFileKind = { 'pdf' : null } |
  { 'image' : null };
export interface InvoiceFileRef {
  'kind' : InvoiceFileKind,
  'gatewayUrl' : [] | [string],
  'mimeType' : string,
  'fileName' : string,
  'objectId' : string,
  'projectId' : [] | [string],
  'sizeBytes' : bigint,
  'uploadedAt' : Timestamp,
}
export interface InvoiceFilter {
  'status' : [] | [PurchaseInvoiceStatus],
  'search' : [] | [string],
  'supplierId' : [] | [Id],
}
export interface InvoiceFilter__1 {
  'to' : [] | [Timestamp],
  'from' : [] | [Timestamp],
  'search' : [] | [string],
}
export interface InvoiceHeaderInput {
  'paymentMethod' : string,
  'supplierName' : [] | [string],
  'invoiceDate' : [] | [Timestamp],
  'invoiceNumber' : [] | [string],
  'paymentMeans' : string,
  'supplierId' : [] | [Id],
  'supplierTaxId' : string,
}
export interface InvoiceLine {
  'kind' : InvoiceLineKind,
  'description' : string,
  'quantity' : bigint,
  'unitPrice' : Money,
  'amount' : Money,
  'unitCost' : Money,
}
export interface InvoiceLineInput {
  'id' : [] | [Id],
  'total' : Money,
  'code' : string,
  'discountRate' : bigint,
  'description' : string,
  'quantity' : bigint,
  'taxRate' : bigint,
  'unitCost' : Money,
}
export type InvoiceLineKind = { 'service' : null } |
  { 'part' : null };
export type InvoiceOrigin = { 'pos' : null } |
  { 'workshopOrder' : null } |
  { 'quote' : null };
export interface InvoicePage {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'items' : Array<PurchaseInvoice>,
}
export interface InvoicePage__1 {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'items' : Array<Invoice>,
}
export interface InvoiceReviewInput {
  'lines' : Array<InvoiceLineInput>,
  'header' : InvoiceHeaderInput,
}
export type InvoiceSort = { 'createdAt' : null } |
  { 'invoiceDate' : null } |
  { 'invoiceNumber' : null };
export interface LaborInput {
  'description' : string,
  'technicianId' : [] | [Id],
  'serviceId' : [] | [Id],
  'price' : Money,
}
export interface LaborItem {
  'id' : Id,
  'description' : string,
  'technicianId' : [] | [Id],
  'serviceId' : [] | [Id],
  'price' : Money,
}
export interface LedgerEntry {
  'id' : Id,
  'concept' : string,
  'date' : Timestamp,
  'kind' : LedgerEntryKind,
  'referenceId' : [] | [Id],
  'referenceType' : [] | [string],
  'category' : string,
  'amount' : Money,
}
export type LedgerEntryKind = { 'expense' : null } |
  { 'income' : null };
export type LineApplyStatus = { 'created' : null } |
  { 'pending' : null } |
  { 'error' : null } |
  { 'updated' : null };
export type LineMatchStatus = { 'new' : null } |
  { 'existing' : null };
export interface LocalBackup {
  'generatedAt' : bigint,
  'json' : string,
  'fileName' : string,
}
export interface Lot {
  'id' : Id,
  'lotNumber' : string,
  'receivedAt' : Timestamp,
  'quantity' : bigint,
  'purchaseId' : [] | [Id],
  'supplierId' : [] | [Id],
  'partId' : Id,
  'unitCost' : Money,
}
export interface LowStockItem {
  'sku' : string,
  'lowStockThreshold' : bigint,
  'name' : string,
  'totalStock' : bigint,
  'partId' : Id,
}
export type Money = bigint;
export interface Motorcycle {
  'id' : Id,
  'model' : string,
  'mileage' : bigint,
  'createdAt' : Timestamp,
  'year' : bigint,
  'customerId' : Id,
  'brand' : string,
  'plate' : string,
}
export interface MotorcycleFilter {
  'search' : [] | [string],
  'brand' : [] | [string],
}
export interface MotorcycleInput {
  'model' : string,
  'mileage' : bigint,
  'year' : bigint,
  'customerId' : Id,
  'brand' : string,
  'plate' : string,
}
export interface MotorcycleListItem {
  'id' : Id,
  'customerName' : string,
  'model' : string,
  'mileage' : bigint,
  'customerPhone' : string,
  'createdAt' : Timestamp,
  'year' : bigint,
  'customerId' : Id,
  'brand' : string,
  'plate' : string,
}
export interface MotorcyclePage {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'items' : Array<MotorcycleListItem>,
}
export type MotorcycleSort = { 'customerName' : null } |
  { 'year' : null } |
  { 'brand' : null } |
  { 'plate' : null };
export interface Movement {
  'at' : Timestamp,
  'id' : Id,
  'kind' : MovementKind,
  'referenceId' : [] | [Id],
  'lotId' : [] | [Id],
  'performedBy' : Principal,
  'quantity' : bigint,
  'partId' : Id,
  'unitCost' : [] | [Money],
  'reason' : [] | [string],
}
export type MovementKind = { 'adjustment' : null } |
  { 'sale' : null } |
  { 'purchase' : null };
export type NotificationSource = { 'pos' : null } |
  { 'service' : null } |
  { 'order' : null } |
  { 'invoice' : null } |
  { 'quote' : null };
export interface OrderFilter {
  'status' : [] | [OrderStatus],
  'search' : [] | [string],
}
export interface OrderInput {
  'motorcycleId' : Id,
  'customerId' : Id,
  'intakeMileage' : bigint,
  'technicianIds' : Array<Id>,
  'problem' : string,
}
export interface OrderPage {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'items' : Array<OrderView>,
}
export interface OrderPart {
  'id' : Id,
  'description' : string,
  'lotId' : [] | [Id],
  'quantity' : bigint,
  'unitPrice' : Money,
  'partId' : Id,
  'unitCost' : Money,
}
export interface OrderPartInput {
  'lotId' : [] | [Id],
  'quantity' : bigint,
  'partId' : Id,
}
export interface OrderPhoto {
  'id' : Id,
  'blob' : ExternalBlob,
  'mimeType' : string,
  'filename' : string,
  'uploadedAt' : Timestamp,
  'uploadedBy' : Principal,
}
export interface OrderPhotoInput {
  'blob' : ExternalBlob,
  'mimeType' : string,
  'filename' : string,
}
export type OrderStatus = { 'cancelled' : null } |
  { 'inRepair' : null } |
  { 'delivered' : null } |
  { 'received' : null } |
  { 'ready' : null };
export interface OrderStatusCount { 'status' : string, 'count' : bigint }
export interface OrderTotals {
  'tax' : Money,
  'total' : Money,
  'partsSubtotal' : Money,
  'laborSubtotal' : Money,
  'taxRate' : TaxRate,
  'subtotal' : Money,
}
export interface OrderView { 'order' : WorkshopOrder, 'totals' : OrderTotals }
export interface PartFacets {
  'categories' : Array<string>,
  'brands' : Array<string>,
}
export interface PartFilter {
  'search' : [] | [string],
  'category' : [] | [string],
  'brand' : [] | [string],
  'lowStockOnly' : [] | [boolean],
}
export interface PartInput {
  'sku' : string,
  'lowStockThreshold' : bigint,
  'name' : string,
  'unit' : string,
  'category' : string,
  'salePrice' : Money,
  'brand' : string,
  'costPrice' : Money,
}
export interface PartPage {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'items' : Array<PartView>,
}
export type PartSort = { 'sku' : null } |
  { 'name' : null } |
  { 'createdAt' : null } |
  { 'stock' : null };
export interface PartView {
  'id' : Id,
  'sku' : string,
  'lowStockThreshold' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'unit' : string,
  'totalStock' : bigint,
  'category' : string,
  'salePrice' : Money,
  'brand' : string,
  'costPrice' : Money,
  'lowStock' : boolean,
}
export interface Payable {
  'status' : PayableStatus,
  'balance' : Money,
  'supplierName' : string,
  'dueDate' : Timestamp,
  'totalPaid' : Money,
  'totalPurchased' : Money,
  'supplierId' : Id,
}
export type PayableStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'overdue' : null };
export interface Payment {
  'at' : Timestamp,
  'id' : Id,
  'method' : PaymentMethod,
  'note' : [] | [string],
  'performedBy' : Principal,
  'purchaseId' : [] | [Id],
  'amount' : Money,
  'supplierId' : Id,
}
export type PaymentCondition = { 'cash' : null } |
  { 'credit' : null };
export interface PaymentInput {
  'method' : PaymentMethod,
  'note' : [] | [string],
  'purchaseId' : [] | [Id],
  'amount' : Money,
  'supplierId' : Id,
}
export type PaymentMethod = { 'mixed' : null } |
  { 'card' : null } |
  { 'cash' : null } |
  { 'transfer' : null };
export interface PaymentMethodBreakdown { 'method' : string, 'total' : Money }
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null };
export interface PosSale {
  'id' : Id,
  'tax' : Money,
  'customerName' : [] | [string],
  'total' : Money,
  'paymentMethod' : string,
  'soldAt' : Timestamp,
  'soldBy' : Principal,
  'invoiceId' : Id,
  'paymentCondition' : PaymentCondition,
  'lines' : Array<PosSaleLine>,
  'discount' : Money,
  'saleNumber' : string,
  'customerId' : [] | [Id],
  'change' : Money,
  'amountReceived' : Money,
  'taxRate' : TaxRate,
  'subtotal' : Money,
}
export interface PosSaleFilter {
  'to' : [] | [Timestamp],
  'from' : [] | [Timestamp],
  'search' : [] | [string],
}
export interface PosSaleInput {
  'creditPlan' : [] | [CreditPlanInput],
  'paymentMethod' : string,
  'paymentCondition' : PaymentCondition,
  'lines' : Array<PosSaleLineInput>,
  'customerId' : [] | [Id],
  'amountReceived' : Money,
}
export interface PosSaleLine {
  'description' : string,
  'discount' : Money,
  'quantity' : bigint,
  'unitPrice' : Money,
  'amount' : Money,
  'partId' : Id,
}
export interface PosSaleLineInput {
  'discount' : Money,
  'quantity' : bigint,
  'partId' : Id,
}
export interface PosSalePage {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'items' : Array<PosSale>,
}
export type Principal = Principal;
export interface ProfitBlock {
  'cost' : Money,
  'commission' : Money,
  'income' : Money,
  'margin' : bigint,
  'marginBps' : BasisPoints,
}
export interface ProfitBreakdown {
  'total' : ProfitBlock,
  'serviceLines' : Array<ServiceProfitLine>,
  'parts' : ProfitBlock,
  'services' : ProfitBlock,
}
export interface Purchase {
  'id' : Id,
  'total' : Money,
  'createdAt' : Timestamp,
  'items' : Array<PurchaseItem>,
  'paidAmount' : Money,
  'supplierId' : Id,
}
export interface PurchaseInput {
  'items' : Array<PurchaseItemInput>,
  'supplierId' : Id,
}
export interface PurchaseInvoice {
  'id' : Id,
  'status' : PurchaseInvoiceStatus,
  'paymentMethod' : string,
  'extractionError' : [] | [string],
  'supplierName' : [] | [string],
  'file' : InvoiceFileRef,
  'createdAt' : Timestamp,
  'confirmedAt' : [] | [Timestamp],
  'confirmedBy' : [] | [Principal],
  'lines' : Array<PurchaseInvoiceLine>,
  'invoiceDate' : [] | [Timestamp],
  'updatedAt' : Timestamp,
  'invoiceNumber' : [] | [string],
  'paymentMeans' : string,
  'supplierId' : [] | [Id],
  'supplierTaxId' : string,
  'extractionStatus' : ExtractionStatus,
}
export interface PurchaseInvoiceLine {
  'id' : Id,
  'matchedPartId' : [] | [Id],
  'total' : Money,
  'applyError' : [] | [string],
  'movementId' : [] | [Id],
  'code' : string,
  'applyStatus' : LineApplyStatus,
  'discountRate' : bigint,
  'description' : string,
  'lineNumber' : bigint,
  'lotId' : [] | [Id],
  'matchStatus' : LineMatchStatus,
  'quantity' : bigint,
  'taxRate' : bigint,
  'unitCost' : Money,
}
export type PurchaseInvoiceStatus = { 'pending' : null } |
  { 'withErrors' : null } |
  { 'confirmed' : null };
export interface PurchaseItem {
  'id' : Id,
  'lotNumber' : string,
  'quantity' : bigint,
  'partId' : Id,
  'unitCost' : Money,
}
export interface PurchaseItemInput {
  'lotNumber' : string,
  'quantity' : bigint,
  'partId' : Id,
  'unitCost' : Money,
}
export interface Quote {
  'id' : Id,
  'status' : QuoteStatus,
  'serviceLines' : Array<QuoteServiceLine>,
  'createdAt' : Timestamp,
  'quoteNumber' : string,
  'updatedAt' : Timestamp,
  'notes' : [] | [string],
  'discount' : Money,
  'motorcycleId' : Id,
  'customerId' : Id,
  'partLines' : Array<QuotePartLine>,
  'taxRate' : TaxRate,
}
export interface QuoteFilter {
  'status' : [] | [QuoteStatus],
  'search' : [] | [string],
}
export interface QuoteInput {
  'serviceLines' : Array<QuoteServiceLineInput>,
  'notes' : [] | [string],
  'discount' : Money,
  'motorcycleId' : Id,
  'customerId' : Id,
  'partLines' : Array<QuotePartLineInput>,
}
export interface QuotePage {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'items' : Array<QuoteView>,
}
export interface QuotePartLine {
  'id' : Id,
  'description' : string,
  'quantity' : bigint,
  'unitPrice' : Money,
  'partId' : Id,
}
export interface QuotePartLineInput {
  'quantity' : bigint,
  'unitPrice' : Money,
  'partId' : Id,
}
export interface QuoteServiceLine {
  'id' : Id,
  'description' : string,
  'quantity' : bigint,
  'serviceId' : [] | [Id],
  'unitPrice' : Money,
}
export interface QuoteServiceLineInput {
  'description' : string,
  'quantity' : bigint,
  'serviceId' : [] | [Id],
  'unitPrice' : Money,
}
export type QuoteSort = { 'total' : null } |
  { 'customer' : null } |
  { 'createdAt' : null } |
  { 'number' : null };
export type QuoteStatus = { 'expired' : null } |
  { 'sent' : null } |
  { 'rejected' : null } |
  { 'accepted' : null } |
  { 'draft' : null };
export interface QuoteTotals {
  'tax' : Money,
  'total' : Money,
  'taxableBase' : Money,
  'servicesSubtotal' : Money,
  'partsSubtotal' : Money,
  'discount' : Money,
  'taxRate' : TaxRate,
  'subtotal' : Money,
}
export interface QuoteView { 'quote' : Quote, 'totals' : QuoteTotals }
export interface Receivable {
  'customerName' : string,
  'status' : ReceivableStatus,
  'total' : Money,
  'balance' : Money,
  'dueDate' : Timestamp,
  'invoiceId' : Id,
  'invoiceNumber' : string,
  'customerId' : [] | [Id],
  'issuedAt' : Timestamp,
  'paidAmount' : Money,
}
export interface ReceivableFilter {
  'status' : [] | [ReceivableStatus],
  'search' : [] | [string],
}
export interface ReceivablePayment {
  'at' : Timestamp,
  'id' : Id,
  'method' : string,
  'note' : [] | [string],
  'invoiceId' : Id,
  'performedBy' : Principal,
  'amount' : Money,
}
export interface ReceivablePaymentInput {
  'method' : string,
  'note' : [] | [string],
  'invoiceId' : Id,
  'amount' : Money,
}
export type ReceivableStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'overdue' : null };
export interface ReceivableSummary {
  'totalOverdue' : Money,
  'totalOutstanding' : Money,
  'openCount' : bigint,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface Service {
  'id' : Id,
  'active' : boolean,
  'code' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'category' : string,
  'laborRate' : Money,
  'estimatedMinutes' : bigint,
}
export interface ServiceCategory {
  'id' : Id,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
}
export interface ServiceCategoryFilter { 'search' : [] | [string] }
export interface ServiceCategoryInput {
  'name' : string,
  'description' : string,
}
export interface ServiceCategoryUsage {
  'serviceCount' : bigint,
  'activeServiceCount' : bigint,
  'category' : ServiceCategory,
}
export interface ServiceFilter {
  'search' : [] | [string],
  'category' : [] | [string],
  'activeOnly' : [] | [boolean],
}
export interface ServiceInput {
  'active' : boolean,
  'code' : string,
  'name' : string,
  'description' : string,
  'category' : string,
  'laborRate' : Money,
  'estimatedMinutes' : bigint,
}
export interface ServicePage {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'items' : Array<Service>,
}
export interface ServiceProfitLine {
  'technicianName' : string,
  'invoiceId' : Id,
  'description' : string,
  'commission' : Money,
  'orderId' : [] | [Id],
  'invoiceNumber' : string,
  'technicianId' : [] | [Id],
  'profit' : bigint,
  'serviceId' : [] | [Id],
  'charged' : Money,
}
export type ServiceSort = { 'code' : null } |
  { 'name' : null } |
  { 'category' : null } |
  { 'laborRate' : null };
export interface StatusChange {
  'at' : Timestamp,
  'to' : OrderStatus,
  'from' : [] | [OrderStatus],
  'performedBy' : Principal,
}
export interface Supplier {
  'id' : Id,
  'taxId' : [] | [string],
  'contactName' : [] | [string],
  'name' : string,
  'createdAt' : Timestamp,
  'email' : [] | [string],
  'address' : [] | [string],
  'phone' : string,
}
export interface SupplierInput {
  'taxId' : [] | [string],
  'contactName' : [] | [string],
  'name' : string,
  'email' : [] | [string],
  'address' : [] | [string],
  'phone' : string,
}
export interface SupplierOrder {
  'id' : Id,
  'sku' : string,
  'createdAt' : Timestamp,
  'createdBy' : Principal,
  'description' : string,
  'quantity' : bigint,
  'supplierId' : Id,
}
export interface SupplierOrderFilter {
  'search' : [] | [string],
  'supplierId' : [] | [Id],
}
export interface SupplierOrderInput {
  'sku' : string,
  'description' : string,
  'quantity' : bigint,
  'supplierId' : Id,
}
export type TaxRate = bigint;
export type TaxResponsibility = { 'agenteRetencionIva' : null } |
  { 'autorretenedor' : null } |
  { 'noAplica' : null } |
  { 'granContribuyente' : null } |
  { 'regimenSimple' : null };
export interface Technician {
  'id' : Id,
  'active' : boolean,
  'code' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'hourlyRate' : Money,
  'email' : [] | [string],
  'specialty' : string,
  'commissionRate' : bigint,
  'phone' : string,
}
export interface TechnicianCommissionSummary {
  'technicianCode' : string,
  'technicianName' : string,
  'netPayable' : Money,
  'pendingLoanCount' : bigint,
  'lineCount' : bigint,
  'technicianId' : Id,
  'pendingLoansAmount' : Money,
  'baseAmount' : Money,
  'commissionAmount' : Money,
  'commissionRate' : bigint,
}
export interface TechnicianFilter {
  'search' : [] | [string],
  'specialty' : [] | [string],
  'activeOnly' : [] | [boolean],
}
export interface TechnicianInput {
  'active' : boolean,
  'code' : string,
  'name' : string,
  'hourlyRate' : Money,
  'email' : [] | [string],
  'specialty' : string,
  'commissionRate' : bigint,
  'phone' : string,
}
export interface TechnicianLoan {
  'id' : Id,
  'commissionPaymentId' : [] | [Id],
  'date' : Timestamp,
  'note' : [] | [string],
  'createdAt' : Timestamp,
  'deductedAt' : [] | [Timestamp],
  'deducted' : boolean,
  'technicianId' : Id,
  'amount' : Money,
}
export interface TechnicianLoanFilter {
  'technicianId' : [] | [Id],
  'pendingOnly' : [] | [boolean],
}
export interface TechnicianLoanInput {
  'date' : Timestamp,
  'note' : [] | [string],
  'technicianId' : Id,
  'amount' : Money,
}
export interface TechnicianWorkload {
  'technician' : Technician,
  'activeOrders' : bigint,
  'orderIds' : Array<Id>,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface UserProfile {
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserView {
  'principal' : Principal,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
}
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export type WhatsAppContactKind = { 'customer' : null } |
  { 'supplier' : null };
export type WhatsAppContext = { 'service' : null } |
  { 'appointment' : null } |
  { 'order' : null } |
  { 'invoice' : null } |
  { 'quote' : null } |
  { 'receivable' : null };
export interface WhatsAppMessageInput {
  'contactKind' : WhatsAppContactKind,
  'context' : WhatsAppContext,
  'referenceId' : [] | [Id],
  'contactId' : Id,
}
export interface WhatsAppMessageResult {
  'contactKind' : WhatsAppContactKind,
  'contactName' : string,
  'hasPhone' : boolean,
  'message' : string,
  'contactId' : Id,
  'phone' : [] | [string],
}
export interface WorkshopOrder {
  'id' : Id,
  'status' : OrderStatus,
  'createdAt' : Timestamp,
  'statusHistory' : Array<StatusChange>,
  'labor' : Array<LaborItem>,
  'cancelledAt' : [] | [Timestamp],
  'updatedAt' : Timestamp,
  'motorcycleId' : Id,
  'customerId' : Id,
  'parts' : Array<OrderPart>,
  'cancelReason' : [] | [string],
  'intakeMileage' : bigint,
  'technicianIds' : Array<Id>,
  'orderNumber' : string,
  'problem' : string,
  'photos' : Array<OrderPhoto>,
}
export interface ZeroInventoryResult { 'affected' : bigint }
export interface ZeroServicesResult { 'deleted' : bigint }
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addLabor' : ActorMethod<[Id, LaborInput], OrderView>,
  'addOrderPart' : ActorMethod<[Id, OrderPartInput], OrderView>,
  'addOrderPhoto' : ActorMethod<[Id, OrderPhotoInput], OrderView>,
  'adjustStock' : ActorMethod<[AdjustmentInput], Movement>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignTechnician' : ActorMethod<[Id, Id], OrderView>,
  'bulkCreateCustomers' : ActorMethod<[Array<CustomerInput>], BulkResult>,
  'bulkCreateParts' : ActorMethod<[Array<PartInput>], BulkResult>,
  'bulkCreateServices' : ActorMethod<[Array<ServiceInput>], Array<Service>>,
  'bulkUpdateCustomers' : ActorMethod<[Array<[Id, CustomerInput]>], BulkResult>,
  'bulkUpdateParts' : ActorMethod<[Array<[Id, PartInput]>], BulkResult>,
  'bulkUpdateServices' : ActorMethod<
    [Array<[Id, ServiceInput]>],
    Array<Service>
  >,
  'cancelOrder' : ActorMethod<[Id, string], OrderView>,
  /**
   * / Completa la autorización OAuth con el código devuelto por Google.
   */
  'completeDriveAuthorization' : ActorMethod<[string, string], DriveAuthResult>,
  'confirmPurchaseInvoice' : ActorMethod<[Id], InvoiceApplyResult>,
  'convertAppointmentToOrder' : ActorMethod<[Id], OrderView>,
  'convertQuoteToInvoice' : ActorMethod<[Id, PaymentMethod], Invoice>,
  'convertQuoteToOrder' : ActorMethod<[Id], OrderView>,
  'createAppointment' : ActorMethod<[AppointmentInput], Appointment>,
  /**
   * / Genera el respaldo y lo sube al Drive del administrador.
   */
  'createBackup' : ActorMethod<[], BackupOutcome>,
  'createCustomer' : ActorMethod<[CustomerInput], Customer>,
  'createExpense' : ActorMethod<[ExpenseInput], Expense>,
  'createExpenseCategory' : ActorMethod<
    [ExpenseCategoryInput],
    ExpenseCategory
  >,
  'createInvoiceFromOrder' : ActorMethod<
    [Id, PaymentMethod, PaymentCondition, [] | [CreditPlanInput]],
    Invoice
  >,
  'createInvoiceFromPosSale' : ActorMethod<
    [
      Id,
      [] | [Id],
      [] | [string],
      Array<InvoiceLine>,
      Money,
      PaymentMethod,
      PaymentCondition,
      [] | [CreditPlanInput],
    ],
    Invoice
  >,
  'createInvoiceFromQuote' : ActorMethod<
    [
      Id,
      Id,
      Array<InvoiceLine>,
      Money,
      PaymentMethod,
      PaymentCondition,
      [] | [CreditPlanInput],
    ],
    Invoice
  >,
  'createMotorcycle' : ActorMethod<[MotorcycleInput], Motorcycle>,
  'createOrder' : ActorMethod<[OrderInput], OrderView>,
  'createPart' : ActorMethod<[PartInput], PartView>,
  'createPosSale' : ActorMethod<[PosSaleInput], PosSale>,
  'createPurchase' : ActorMethod<[PurchaseInput], Purchase>,
  'createPurchaseInvoiceDraft' : ActorMethod<
    [CreateInvoiceInput],
    PurchaseInvoice
  >,
  'createQuote' : ActorMethod<[QuoteInput], QuoteView>,
  'createService' : ActorMethod<[ServiceInput], Service>,
  'createServiceCategory' : ActorMethod<
    [ServiceCategoryInput],
    ServiceCategory
  >,
  'createSupplier' : ActorMethod<[SupplierInput], Supplier>,
  'createSupplierOrder' : ActorMethod<[SupplierOrderInput], SupplierOrder>,
  'createTechnician' : ActorMethod<[TechnicianInput], Technician>,
  'createTechnicianLoan' : ActorMethod<[TechnicianLoanInput], TechnicianLoan>,
  'deleteAppointment' : ActorMethod<[Id], boolean>,
  'deleteExpense' : ActorMethod<[Id], boolean>,
  'deleteExpenseCategory' : ActorMethod<[Id], boolean>,
  'deleteOrder' : ActorMethod<[Id], boolean>,
  'deleteQuote' : ActorMethod<[Id], boolean>,
  'deleteService' : ActorMethod<[Id], boolean>,
  'deleteServiceCategory' : ActorMethod<[Id], boolean>,
  'deleteTechnician' : ActorMethod<[Id], boolean>,
  'deleteTechnicianLoan' : ActorMethod<[Id], boolean>,
  /**
   * / Revoca la conexión con Google Drive del administrador.
   */
  'disconnectDrive' : ActorMethod<[], undefined>,
  /**
   * / Genera la copia de seguridad local: devuelve el mismo JSON que el
   * / respaldo a Drive y el nombre del archivo con fecha y hora, para que el
   * / frontend lo descargue en el equipo del usuario. Es una **consulta** de
   * / solo lectura: no espera a ningún canister ni muta estado.
   */
  'downloadLocalBackup' : ActorMethod<[], LocalBackup>,
  'execute' : ActorMethod<[string], Result>,
  'exportCustomersAggregated' : ActorMethod<[], Array<CustomerExportRow>>,
  'exportInventoryCsv' : ActorMethod<[], Array<InventoryCsvRow>>,
  'findTechnicianByCode' : ActorMethod<[string], [] | [Technician]>,
  'getAccountingReport' : ActorMethod<[AccountingPeriod], AccountingReport>,
  'getAccountingSummary' : ActorMethod<[AccountingPeriod], AccountingSummary>,
  'getApiDoc' : ActorMethod<[], string>,
  'getAppointment' : ActorMethod<[Id], [] | [Appointment]>,
  'getBusinessSettings' : ActorMethod<[], BusinessSettings>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommissionPayment' : ActorMethod<[Id], [] | [CommissionPayment]>,
  'getCommissionReport' : ActorMethod<[CommissionPeriod], CommissionReport>,
  'getCompanyProfile' : ActorMethod<[], CompanyProfile>,
  'getCustomer' : ActorMethod<[Id], [] | [Customer]>,
  'getCustomerDetail' : ActorMethod<[Id], [] | [CustomerDetail]>,
  'getDashboardSummary' : ActorMethod<[], DashboardSummary>,
  /**
   * / Estado de la conexión con Google Drive del administrador. Es tolerante a
   * / credenciales ausentes: nunca lanza un trap por configuración faltante y
   * / siempre incluye `configuration` con las variables ausentes. Es una
   * / actualización (no consulta) porque lee las variables de entorno del
   * / canister, que requieren la capacidad `<system>`.
   */
  'getDriveConnectionStatus' : ActorMethod<[], DriveConnectionStatus>,
  'getExpense' : ActorMethod<[Id], [] | [Expense]>,
  'getExpenseCategory' : ActorMethod<[Id], [] | [ExpenseCategory]>,
  'getExpenseSummary' : ActorMethod<[ExpenseFilter], ExpenseSummary>,
  'getInventoryValuation' : ActorMethod<[], InventoryValuation>,
  'getInvoice' : ActorMethod<[Id], [] | [Invoice]>,
  'getOrder' : ActorMethod<[Id], [] | [OrderView]>,
  'getPart' : ActorMethod<[Id], [] | [PartView]>,
  'getPayable' : ActorMethod<[Id], [] | [Payable]>,
  'getPosSale' : ActorMethod<[Id], [] | [PosSale]>,
  'getPurchaseInvoice' : ActorMethod<[Id], [] | [PurchaseInvoice]>,
  'getQuote' : ActorMethod<[Id], [] | [QuoteView]>,
  'getReceivableSummary' : ActorMethod<[], ReceivableSummary>,
  'getService' : ActorMethod<[Id], [] | [Service]>,
  'getServiceCategory' : ActorMethod<[Id], [] | [ServiceCategory]>,
  'getSupplier' : ActorMethod<[Id], [] | [Supplier]>,
  'getTechnician' : ActorMethod<[Id], [] | [Technician]>,
  'getTechnicianCommissionSummary' : ActorMethod<
    [Id, CommissionPeriod],
    [] | [TechnicianCommissionSummary]
  >,
  'getTechnicianLoan' : ActorMethod<[Id], [] | [TechnicianLoan]>,
  'getTechnicianWorkload' : ActorMethod<[Id], [] | [TechnicianWorkload]>,
  'importInventoryCsv' : ActorMethod<
    [Array<InventoryImportRow>],
    InventoryImportResult
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAppointments' : ActorMethod<[AppointmentFilter], Array<Appointment>>,
  /**
   * / Lista los respaldos recientes desde el Drive del administrador.
   */
  'listBackups' : ActorMethod<[], BackupListOutcome>,
  'listCommissionLines' : ActorMethod<
    [[] | [Id], CommissionPeriod],
    Array<CommissionLine>
  >,
  'listCommissionPayments' : ActorMethod<
    [CommissionPaymentFilter],
    Array<CommissionPayment>
  >,
  'listCustomers' : ActorMethod<[[] | [string]], Array<Customer>>,
  'listCustomersPage' : ActorMethod<
    [CustomerFilter, CustomerSort, bigint, bigint],
    CustomerPage
  >,
  'listCustomersPageDir' : ActorMethod<
    [CustomerFilter, CustomerSort, boolean, bigint, bigint],
    CustomerPage
  >,
  'listExpenseCategories' : ActorMethod<
    [ExpenseCategoryFilter],
    Array<ExpenseCategoryUsage>
  >,
  'listExpenses' : ActorMethod<[ExpenseFilter, bigint, bigint], ExpensePage>,
  'listInvoices' : ActorMethod<
    [InvoiceFilter__1, bigint, bigint],
    InvoicePage__1
  >,
  'listLedgerEntries' : ActorMethod<[AccountingPeriod], Array<LedgerEntry>>,
  'listLots' : ActorMethod<[Id], Array<Lot>>,
  'listMotorcycleCountsByCustomers' : ActorMethod<
    [Array<Id>],
    Array<[Id, bigint]>
  >,
  'listMotorcycles' : ActorMethod<[Id], Array<Motorcycle>>,
  'listMotorcyclesPage' : ActorMethod<
    [MotorcycleFilter, MotorcycleSort, bigint, bigint],
    MotorcyclePage
  >,
  'listMotorcyclesPageDir' : ActorMethod<
    [MotorcycleFilter, MotorcycleSort, boolean, bigint, bigint],
    MotorcyclePage
  >,
  'listMovements' : ActorMethod<[Id], Array<Movement>>,
  'listOrders' : ActorMethod<[OrderFilter, bigint, bigint], OrderPage>,
  'listPartFacets' : ActorMethod<[], PartFacets>,
  'listParts' : ActorMethod<[PartFilter, PartSort, bigint, bigint], PartPage>,
  'listPartsDir' : ActorMethod<
    [PartFilter, PartSort, boolean, bigint, bigint],
    PartPage
  >,
  'listPayables' : ActorMethod<[], Array<Payable>>,
  'listPayments' : ActorMethod<[[] | [Id]], Array<Payment>>,
  'listPosSales' : ActorMethod<[PosSaleFilter, bigint, bigint], PosSalePage>,
  'listPurchaseInvoices' : ActorMethod<
    [InvoiceFilter, InvoiceSort, bigint, bigint],
    InvoicePage
  >,
  'listPurchases' : ActorMethod<[[] | [Id]], Array<Purchase>>,
  'listQuotes' : ActorMethod<
    [QuoteFilter, QuoteSort, bigint, bigint],
    QuotePage
  >,
  'listReceivables' : ActorMethod<[ReceivableFilter], Array<Receivable>>,
  'listServiceCategories' : ActorMethod<
    [ServiceCategoryFilter],
    Array<ServiceCategoryUsage>
  >,
  'listServices' : ActorMethod<
    [ServiceFilter, ServiceSort, bigint, bigint],
    ServicePage
  >,
  'listSupplierOrders' : ActorMethod<
    [SupplierOrderFilter],
    Array<SupplierOrder>
  >,
  'listSuppliers' : ActorMethod<[[] | [string]], Array<Supplier>>,
  'listTechnicianLoans' : ActorMethod<
    [TechnicianLoanFilter],
    Array<TechnicianLoan>
  >,
  'listTechnicianWorkload' : ActorMethod<[], Array<TechnicianWorkload>>,
  'listTechnicians' : ActorMethod<[TechnicianFilter], Array<Technician>>,
  'listUsers' : ActorMethod<[], Array<UserView>>,
  'lowStockParts' : ActorMethod<[], Array<PartView>>,
  'markInvoicePaid' : ActorMethod<[Id, PaymentMethod], Invoice>,
  'notifyCustomer' : ActorMethod<
    [CustomerNotificationInput],
    CustomerNotificationResult
  >,
  'payTechnicianCommission' : ActorMethod<
    [CommissionPaymentInput],
    CommissionPayment
  >,
  'prepareWhatsAppMessage' : ActorMethod<
    [WhatsAppMessageInput],
    WhatsAppMessageResult
  >,
  'registerInstallmentPayment' : ActorMethod<[Id, bigint], Invoice>,
  'registerPayment' : ActorMethod<[PaymentInput], Payment>,
  'registerReceivablePayment' : ActorMethod<
    [ReceivablePaymentInput],
    ReceivablePayment
  >,
  'removeLabor' : ActorMethod<[Id, Id], OrderView>,
  'removeOrderPart' : ActorMethod<[Id, Id], OrderView>,
  'removeOrderPhoto' : ActorMethod<[Id, Id], OrderView>,
  'runPurchaseInvoiceExtraction' : ActorMethod<[Id], PurchaseInvoice>,
  'saveCallerUserProfile' : ActorMethod<[string], UserProfile>,
  'schema' : ActorMethod<[], string>,
  'setUserRole' : ActorMethod<[Principal, UserRole], UserView>,
  /**
   * / Inicia la autorización OAuth (PKCE) de la cuenta propia del
   * / administrador.
   */
  'startDriveAuthorization' : ActorMethod<[], DriveAuthStart>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unassignTechnician' : ActorMethod<[Id, Id], OrderView>,
  'updateAppointment' : ActorMethod<[Id, AppointmentInput], Appointment>,
  'updateAppointmentStatus' : ActorMethod<[Id, AppointmentStatus], Appointment>,
  'updateBusinessSettings' : ActorMethod<[BusinessSettings], BusinessSettings>,
  'updateCompanyProfile' : ActorMethod<
    [CompanyProfileRawInput],
    CompanyProfile
  >,
  'updateCustomer' : ActorMethod<[Id, CustomerInput], Customer>,
  'updateExpense' : ActorMethod<[Id, ExpenseInput], Expense>,
  'updateExpenseCategory' : ActorMethod<
    [Id, ExpenseCategoryInput],
    ExpenseCategory
  >,
  'updateLaborTechnician' : ActorMethod<[Id, Id, [] | [Id]], OrderView>,
  'updateMotorcycle' : ActorMethod<[Id, MotorcycleInput], Motorcycle>,
  'updateOrderStatus' : ActorMethod<[Id, OrderStatus], OrderView>,
  'updatePart' : ActorMethod<[Id, PartInput], PartView>,
  'updatePurchaseInvoiceReview' : ActorMethod<
    [Id, InvoiceReviewInput],
    PurchaseInvoice
  >,
  'updateQuote' : ActorMethod<[Id, QuoteInput], QuoteView>,
  'updateQuoteStatus' : ActorMethod<[Id, QuoteStatus], QuoteView>,
  'updateService' : ActorMethod<[Id, ServiceInput], Service>,
  'updateServiceCategory' : ActorMethod<
    [Id, ServiceCategoryInput],
    ServiceCategory
  >,
  'updateSupplier' : ActorMethod<[Id, SupplierInput], Supplier>,
  'updateTechnician' : ActorMethod<[Id, TechnicianInput], Technician>,
  'zeroInventory' : ActorMethod<[], ZeroInventoryResult>,
  'zeroServices' : ActorMethod<[], ZeroServicesResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];